sudo: required

language: go 

services:
  - docker

go:
  - 1.5.1

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - cd discount-go
  - make docker-push
  - cd ..

env:
  global:
  - secure: F54IEz5tgpJIBVHC2DjXmu6kFwXPazoRTjI7EH6wKquShXzVExP7xi2Dmfvn74TpfW0nimZ0xqwCR41UNk3FM7kMitLsVGlep6Ks594QxP2lS5smIuL2jcHwNqFhphEGwn5S8RKB4s+hfoBzzHBWSZlaHDfj3/nCIZLSjpU4gzBWEVa5XG+JSnAvxuO+mIxz+GerQTrvOfePWumcE4YeYE5q7I9383882vGR0i5yTzBBR51QKhRqxZkmTUmsvId7HKN7oRa49kUBCD/pqZLB85IGZsIqRkt0iWtWgTvG2qPYPkoZN2LvJMHpIJCmArYXOjFbQnTJx3ugqkg9Wh/tXUZAHtrZAnJ3Xa5cVgfq58vFgflBGQeseYelp24VPEQm2MdsevqS+86vYzZeQhjrWnGL5bpcJtMO1E8rt20+K6VSTlcrxhKs00dxendoZ+A9Xyspt8H90u97e/vY6oFTePuCT0+QkVy0q8im0iJe1i2CNGYy7Bp5D+TQfR8Qe6ZzVZb21/7p61Bry869uwC/9mFRCxRpMQqQmNQoyG8+1QWzCBWOK1fP8+t1Qzot/MTOaesGnUy6bspGtowBjTNzl9oBXcg/7TydEfHUHOFJeTPMoU/le8FHK25AFEJA7WoZtL934lj9sV7wXhp/yhrSuS7YXJh6G9JTiunZOZlma0E=
  - secure: Q8C0HJFaJcFoAvz2jms0vx259I+dxlD6hP2eilZ3bsbB4SNeFTZ00FRATBLiKQd+2pmdR8a8l4Zzbvg4SmaQAnbV+DE6Su6kYvMxRK3XusQTKF58aNvkk8UNNaXwclaz8KhZA93YigVqKs6zGdb5xQ0jw1e8hBrkeMEdSrvnScZNTZwoBbpR0g4zhANP2BEyyRstSR43Ah33Wu5/YBjZAl4zSImUthjG64qO+69+EFE5IJODv/YHe/owsAUEK4aPV3p8YmZP50paafLNL/fQJfxY2ceYB00L/VMQrql3WC6ABTpDpD+9OHFLxDVgPfF5hud0HF5S7wvxpA2dgRtKiO9GUsr84ZdISKDcMLkEtQnA/Ruintfb7JuK2W4CJQJAJsBKJKG06/M7PSy++hikg+/F8AyIpgIQVoA+Va+jA5rWpt3DfRAD8noq6z6iC9Nkba0746H3t2RJH0hrvAH//NUdvkNUwNYFgo3KmTErfp9j0OLuNnjBj8wVh1cpGVyZAxHlztvFQNlC5fj/uw39n/SwU8mvDkWEmcwgnWjHaKuS7bPML17q/M0zzHJ5lwmq/XuKuQfQuGyJ0G7gycxEChGsq2bh+KqLPuJ9OkSyxA6PArShbX9p8WWA5he8SxR7FbNH49ABGRpaWcNmCWZNgtoS8K2Vx+Y7XIOBp34/AjQ=
  - secure: p13qmuaHubmttZID8Q/xO/3/0sdejdS9vyRrUMvwD4w4u7EG1ER4tEbJFYXT7bdWOqbJFPRUv1mh02F5jryetzTCqf1xwFVKcxVKa2IGCiccyBBcSq2JTk7k0oFjSZXa8gHMedVA4TpYBmdFJXT4B33ngIY550oP9vYbcLI7Ur2i1zmYdNPPQ/W/J1RPyIy2Cbj3BgsW+8E3PwVcJpbqHh3vnrUjiGQYCRy+GDXvWrnRxrtSW/gDgBO8au8AqXp/JHAlJ9QpXoj+hAOmVi9trnl4H/Up1h1WpIEMhP/U6R49XnFJ8yfnU+pZiANtju6lcM/qutGvcuzpAG7kb2UP4+wRz62Y3uJKwRHLnbn4XFm7DRklq/mmULafMPnA55rHmYj+L3DGMYJJVwJ663Nskl8mzsuP/5w5M/hlEvo+o2EYpO1dJb/cf/nF/dcli+F8x7GccHX74+NlsiKX1869gpo4SPq/01dvdSdpqzkWB+8VPbDotUxO+dM7bx+sxQWjTtz2bm8WhNr2Q+leY006VFxg0ucE88wVkKJlJZvK7697UU9ntmwoTlS3UzFsoTAYm7N/rClrtQ36JoudG5Y6HHNJIbfu8fF+Nd13gw+Qa5otRV+12U4CigCtD8akdI9HoClBSf7qGG+gsOFVkSiWYaud7qF3fDV51geVH3EzAQU=
