sudo: required

language: go 

services:
  - docker

go:
  - 1.5.1

script:
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker -v
  - make publish

env:
  global:
  - secure: buElfA7Q8YlipuEOhO4txd+PI2jnTqisY9npI3s4XarnqLtCWY1NiqVRVDsyX3yOHpvriI1TGHPb3Bh+eIu6d54E0D5PYAafvpFkIVTFnNHYJf0AU7oc/HYCiuxcllpWPVEHaCJUi+8KtN7I/xwni5VyLu9Ax+TbLFurdtcQpuiPyjDVgG7wG3WP3uTwY3FfiFv9nFi/JUb5JznPyp6q8c2yRvhz1ISGZ2Ig4T42AOc2uF7FpaYyiGE84i9tGoQWJOyBTxqye+aJbWANBl3f2AmWOl+7cFRs8Hcs7zlxgM1NYq3NV6d5WJVyucU+7dMoh2htplt3fIe1Vm+qkG2yep4YROMbdo+p5gDQJJ0cjAykbjf3pAjcDsM/d5Zey84v33/z5qVCzRtEhMKETPFcbdAvt6tcemtDNTFu6n9ApvYeg6FV7Nmm50p6ltBSGdAlSf4o7oKc+X5ndb1plHih1ZUUIa65DFwHywKTCv0/gAruJDhr3XcTZj+UJpTlV3FrXZzOD9vOR6vUPQg4KL8DOzpm+DY4sntJdFLCA9Cx1ygSlDt3vBFYGFuBG1LUzIuXDV+oIysBe1CKQJ6NbvpVmKCX8NwThqwBQSooK2WuAjx7M1OUT7mZ2jM9hqwmBnjCAA6M1SB3lvKRzJg/z7+HH/sFKUEvkMNfqIwtbpns4kg=
  - secure: rRE5aW5Q7gh3WFSIE9Ps0U3hG/4NDX4cP5zMhUv1JUEYJI7vB4Fw5v33kpsHzDNjfoBLIqkjyXjLzy7NbWyXhaNA86CX7J3HKdrdfNLk9MtfxWu9JsbI0gdYEkcTL1Y/rvBNvwDJQzGAO0g+SYz7x8+j1TAWNPlCcsIMljUdaU8fYacxbAmA6pzqCI7xnCMHM2r+oTKNLNE8nvzUHNe9GMqMWRRZyRB5YodTyqemz9RzfC3mFB4iaJRPA6RULbWm16jM2TjCxaDFSIZtMMSxTbfej9rpt6IunZhg0afEGsSv4l3oLpXy0Q02xWYfKCqw4xCJxiFyxtBH4LuGo5W74gvUSOQa2gfi7Brb6uj4/kE+PQkKAzwOGQwekkQVW66/SDy7nQs+iR+trGdpCRcpxY+mDcomjo7B6pn3kvyz13884M1x76P0GnodrOX3bqUSWkId39pRuioZOc6MEq23Jzev1qSZYa+l3c9CErN0D1bu/Oe+I8iDOAplRHJMWUW9GqYRTzcZ4tbF6L6jCOgs6AH73l2bs+vDTAL4S4Hw5S1zgrgudE2mLeqwIB2yVeiOdNyLRdyq64iiiwcGxySJWPLjqY3YNc10HJPsWUsVVMCgSDrVG8CXl83wXa12SeYv08zT1dIg3oN5Z1C5WAx8NgeI/SzLfvQMUWAxXmInPbs=
  - secure: gBdziQuxjhhzz8dt0Mq/8XGBkAu+rtHStpJhQuKN5cl9CzqK00irDw+ax05sujpCcsB8qH/kP+kcQQB9JFFzPGFHGxFoDeyjz+cl7NF4zGZJkzncvcqBO/zWB2oEaTb6pJl8O9pepQsqvH89blCgLNUf+61Cmg/DwXSsF1/DWVy3GWMWwV5Op2Ch+mj8P1yk4h4SiuPAL9epbUQYoaoISti5YUo6AbSk6rPn5qkJ/E3k3FzjAZgcdso9zrfzcBvZkf3PbHq3y3UiXCg7Dydy8wWOpFpkY+n2pVdNLOmREvSI9SDbkHc318PTnaJDU9F3PYAClVQy25PV1Pp2F/ibjWAFe00TeIDLNOi+dAj/atiXnUgh7afu0D1ADJbaXDnQ7xj0M8ZGBSihLqdlB7NX21huR0FKzOVrTLoRad6MZDIvR936dzW4ICXz4AQOjX+dLZ2TympG2SZDgw5ixalSFG3PJZhPxlH/NEpM8r1lH077PLrEp81fv5yGxf8l6+ArzNi46xB/txgOADJUsfNnHnuRNoyYxGnILAexR57i5BxEVUHYuD6/TImieg4ckDx0EZnnuoSUfGRtwPl0Y9noYkaak3BGaq/WOwb/s5ok/JeCQ/5osmt76s4uWzQzn6GL6WUymF9Y3vMjIUsQ+VvTaSu36wQM0kX5PlAkhBPULIc=