sudo: required

language: go 

services:
  - docker

go:
  - 1.5.1

script:
  - cd discount-go
  - make test
  - make build
  - make docker
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - make docker-push
  - cd ..

env:
  gobal:
    - secure: "oGb0Vq30FLAYpnkzYBmHy+q+s1s2XalQi+4vzfDQVfdgBV/U4qTbk6JyAQbV2B4sUWX7hJckVB1C+3akjt7eJqyaINE7AoqR+oxxVCJJucbi2lmyWri3fzsC7DsWdIIlqeo439DyWiuE/0hYAoUDjaycGWPY+VckaKgwtHnIaKfZgW19GIZ+Or8nb2NOCGIcfF3KLpVUthV87lzPOWnfApqnfQ5M1MTPCpXDMlcUIot+2vp4/N+56cobjs0L3oWiO3aBw57t/BV7Hdb5kPhP/ui3Hgd0M8DGUa4oB41atWts0K4+a3odus3xAENzzZAjoKDaDGvpHptmJtlJB7FWjcju3Tw1uBLn1inUoGzyxu9aNYCjV7vrmzfF+W8NyNYF4qVzF5iXx2sxOF+WxwhGoSw6tJLk/YZczs9KJdl0hWvHkpMj8n4wBH8/f8uA+iNKqHeAdVRIwlgc/ghNGPr0TtJghwYpNr2lEjo/QUNa4SNY236fjbQMkxDPOX/lhXFiskMUPVq2Ujp2gfkRronmDJ5te8GKsomSrbiEfk4ABc5FFeBeKQx3rZWYIiowO3aVMazu557k4qkV/SA3JrEVyaZBhdUip/z+2oao8eN/9OdgijDKfYgZkGecSMRHie2x8JAwHmRMW9ek3KeIghX36L441pxR8J5qrdbWaqoay1c="
    - secure: "WKzjr3jKqBtf2Nk5fIJvo5s6UPPdiIsHdr0ioQWty80XSlNGzwxhuMPvJ4pZ1+iIEolFWXenuJS1UIsxzeLMaCvMw/auXSOK3nFMgBzu/v7/JydtECqZhPC2F5aHhoZrmWhqaYAYncB2mHORwz/YoenCeIhPu5cN1PPEKJt474y7drvCJAinnFxsCB4X8sZOG9dxs2KJwY59ZBhd3+57W8Wy0HBV7iTrrQYdWsru2A/uUj5f3akSOCoXB8fPpaIAgR6x9Sc1rFfozQz1SNAqCU+f/iRAHbA57BC1EsLj4IlmG2UVLNuLJyqtTNf6KmIdSVF86XyI+Ts/McZG0OdIDvgXECnf2OhhvHh1IYkwJBMji3PgC6pBrNz6qhfR7xERtRamAAjxW4eWEfigOiMglfXDOclQLVnr1sZpiHie/olnqAA99Y4Zwa+p9JD435axpIfepb8SMQfaTLxOZRHFpip/HGn9PWX0Ch6tGpt7+SYEuQrLq8njDCv7D4ndxjUZ/5WjfhYEII1tcAprldNyG2lceeJpQW5Xgc/WsTZJU9CKLj2W/T63iH8dalMzrh3hoQwb4KiH2875S3UlpCl5uISmgjduKLuT8oCpK1Izmwbn4jm/tG13Yyo065EtzWiWVYwskTz90RajfUTLenP1vhoC3BFL9UrU6dahSdZx4rk="
    - secure: "nxDYk4+qK2jKC8+NpOx8CDR3TSxLs7SrzZDI2mveDQbxCm6bgd1FOyORTwlb1H8tedJrQMlA92wwmPcoekO19L2QLexoJJVn9Dohltic+lnfSswCgcNn1mwKeqllaNhALAdisZQTqWyxgtkxTW6dSJ4Pz1Tncfd0qSGBxEZnkufU7nojDhaLiRr5ninxmHNdVyGtE4o2UoqtcjB8J8ssx297MMOJXc9ea3waRLR2A5UnzCUKw9fTtaO9hsL8le2Sy8jlk4yTZZoeT81fOQwPeXXOqOABhl6rSCPT43DC4AkiGbv0Sds460po5rpMUPxIgP/K6+JBcGwQP5BO7E5mEVnO7AqkfqRp5t9eSjXKu9zgu5PsaBGf38pfVLRIiUK5CUTcx5uEpbklP8hw0ywb3/bIR2A8osCdZihaYXfsRFUPSAua2/o6SmpuHbfyR6McPOwx7VJH1T8ObiAL9+Gxb/FfmMhdlkpKAtYsTvlrEvRslCZXev+sQSl/Q2sP5vv5mbLIa+8fWNZy7bgWTJGpn2JL3nE8aqyXhcxLg8KDuPhDXV7oBNql1TWAEsllavC0PGcU5Nvap52cdBWXw9cqlhqqWB+3gpOMmTa/7gERgCrFHoS5eJ4lc+r0GxlBFkaSO9KCwyauNnh7ELDsmQBN9yex9JLPTygyj3ZHXFgwLEo="
