apiVersion: v1
kind: Pod
metadata:
  name: config-feeder
  namespace: default
spec:
  containers:
  - image: sogyo/sogyo-shop-config-feeder
    command:
      - sleep
      - "600"
    name: config-feeder
  restartPolicy: Always
