apiVersion: v1
kind: Service
metadata:
  name: discount-aspnet-service
  labels:
    app: discount-aspnet
type: LoadBalancer
spec:
  ports:
  - port: 80
    name: service
    targetPort: 5004
    protocol: TCP
  selector:
    app: discount-aspnet
  ClusterIP: 10.199.1.11
