apiVersion: v1
kind: ReplicationController
metadata:
  name: sogyo-shop-discount-aspnet-controller
spec:
  replicas: 2
  selector:
    app: discount-aspnet
  template:
    metadata:
      labels:
        app: discount-aspnet
    spec:
      containers:
      - name: sogyo-shop-discount-aspnet
        image: sogyo/sogyo-shop-discount-aspnet
        ports:
        - containerPort: 5004
