apiVersion: v1
kind: Service
metadata:
  name: discount-go-service
type: LoadBalancer
spec:
  ports:
  - port: 80
    name: service
    targetPort: 8080
    protocol: TCP
  selector:
    app: discount-go
  ClusterIP: 10.199.1.12