apiVersion: v1
kind: ReplicationController
metadata:
  name: sogyo-shop-discount-go-controller
spec:
  replicas: 2
  selector:
    app: discount-go
  template:
    metadata:
      labels:
        app: discount-go
    spec:
      containers:
      - name: sogyo-shop-discount-go
        image: sogyo/sogyo-shop-discount-go
        ports:
        - containerPort: 8080
        