apiVersion: v1
kind: Service
metadata:
  name: frontend-angular-service
type: LoadBalancer
spec:
  ports:
  - port: 80
    name: service
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend-angular
  ClusterIP: 10.199.1.15
