apiVersion: v1
kind: ReplicationController
metadata:
  name: sogyo-shop-frontend-angular-controller
spec:
  replicas: 3
  selector:
    app: frontend-angular
  template:
    metadata:
      labels:
        app: frontend-angular
    spec:
      containers:
      - name: sogyo-shop-frontend-angular
        image: sogyo/sogyo-shop-frontend-angular
        ports:
        - containerPort: 80
